apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: game-2048
          image: bennanimohameddevopscloud/game-2048:1.0.0-30
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: myregistrysecret

---
apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
spec:
  selector:
    app: game-2048
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer 
