# kubecost-deployment.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubecost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost
  namespace: kubecost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecost
  template:
    metadata:
      labels:
        app: kubecost
    spec:
      containers:
        - name: kubecost
          image: quay.io/kubecost/cost-analyzer:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: kubecost
  namespace: kubecost
spec:
  selector:
    app: kubecost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer # Use 'NodePort' or 'ClusterIP' as per your environment
