apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Match the container port
  type: LoadBalancer # Change to NodePort or ClusterIP as needed
